on:
  push:
  workflow_dispatch:
    inputs:
      who:
        description: 'Who to greet'
        required: true
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: SaqlainSentry/hello-world-composite-action@v2
        with:
          who-to-greet: ${{ inputs.who||'Mona the Octocat'}}
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
